[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/status"
  status = 200

[[redirects]]
  from = "/api/discord"
  to = "/.netlify/functions/discord"
  status = 200